<?php
// Include the connection file
include 'dbh.php';

// Function to display the privacy policy content
function display_privacy_policy() {
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Privacy Policy - SacroAI Diagnosis</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
            }
            .container {
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #fff;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1, h2, h3 {
                color: #333;
            }
            p {
                color: #555;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Privacy Policy</h1>
            <p>Welcome to SacroAI Diagnosis, a medical application designed to monitor and diagnose health conditions, especially focusing on sacroiliac joint issues post-surgery. This Privacy Policy explains how we collect, use, and protect your personal data when you use our service.</p>
            
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words with initial letters capitalized have meanings defined under the following conditions. These definitions will have the same meaning whether in singular or plural form.</p>
            
            <h3>Definitions</h3>
            <ul>
                <li><strong>Account:</strong> A unique account created for You to access our Service or parts of it.</li>
                <li><strong>Affiliate:</strong> An entity controlling, controlled by, or under common control with a party.</li>
                <li><strong>Application:</strong> Refers to SacroAI Diagnosis, the software provided by the Company.</li>
                <li><strong>Company:</strong> Refers to SacroAI Diagnosis.</li>
                <li><strong>Country:</strong> Tamil Nadu, India.</li>
                <li><strong>Device:</strong> Any device capable of accessing the Service, such as a computer, cellphone, or tablet.</li>
                <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> The Application.</li>
                <li><strong>Service Provider:</strong> Any person or entity processing data on behalf of the Company.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
                <li><strong>You:</strong> The individual or entity accessing or using the Service.</li>
            </ul>
            
            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Health data (e.g., sacroiliac joint assessment, post-surgery recovery data, etc.)</li>
            </ul>
            
            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device\'s IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data. When accessing the Service via a mobile device, additional information such as device type, unique ID, IP address, operating system, and browser type may also be collected.</p>
            
            <h4>Health Data</h4>
            <p>As part of the service, We may collect health-related data such as updates on your sacroiliac joint health, pain levels, mobility, and other metrics that are essential for monitoring your condition. This data is used to assist in monitoring your health and reducing the need for frequent doctor consultations.</p>
            
            <h2>Sharing Your Personal Data</h2>
            <ul>
                <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service, manage health data, and assist in reducing the frequency of consultations.</li>
                <li><strong>For Business Transfers:</strong> During mergers, sales, or acquisitions.</li>
                <li><strong>With Affiliates:</strong> Including our parent company and other subsidiaries under common control.</li>
                <li><strong>With Business Partners:</strong> To offer health-related products, services, or promotions.</li>
                <li><strong>With Other Users:</strong> When interacting publicly or sharing personal information.</li>
                <li><strong>With Your Consent:</strong> For any other purpose with your explicit consent.</li>
            </ul>
            
            <h2>Retention of Your Personal Data</h2>
            <p>We will retain Your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy and to comply with legal obligations. Health data will be retained as long as required for monitoring your condition and assisting in minimal doctor consultations.</p>
            
            <h2>Transfer of Your Personal Data</h2>
            <p>Your data may be processed and maintained on computers located outside of your jurisdiction. Your consent to this Privacy Policy signifies agreement to such transfers. We will ensure adequate security measures are in place for any such data transfers.</p>
            
            <h2>Disclosure of Your Personal Data</h2>
            <h3>Business Transactions</h3>
            <p>Your data may be transferred in case of mergers, acquisitions, or asset sales. We will notify you before such data is transferred.</p>
            
            <h3>Law Enforcement</h3>
            <p>We may disclose your data if required by law or in response to valid requests from public authorities.</p>
            
            <h3>Other Legal Requirements</h3>
            <p>We may disclose your data to comply with legal obligations, protect our rights or property, prevent wrongdoing, protect safety, or against legal liability.</p>
            
            <h2>Security of Your Personal Data</h2>
            <p>We strive to protect your data but cannot guarantee absolute security. We use commercially acceptable methods to safeguard your Personal Data.</p>
            
            <h2>Children\'s Privacy</h2>
            <p>Our Service does not target individuals under 13. We do not knowingly collect data from this age group. If you are a parent or guardian and become aware of such data collection, please contact us.</p>
            
            <h2>Changes to this Privacy Policy</h2>
            <p>We may update this Privacy Policy and will notify you of any changes by posting the new policy on this page. We will also notify you via email or a prominent notice on our Service. Please review the policy periodically for updates.</p>
            
            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:tappetasumithra@gmail.com">tappetasumithra@gmail.com</a>.</p>
            
            <p>© 2024 SacroAI Diagnosis. All rights reserved.</p>
        </div>
    </body>
    </html>';
}

// Call the function to display the privacy policy
display_privacy_policy();
?>
